# Server
server:
  port: 8090
  servlet:
    context-path: /

# DataBase
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${{secrets.db_url}}
    username: ${{secrets.db_username}}
    password: ${{secrets.db_password}}
    url: jdbc:log4jdbc:mysql://db-2voai5-kr.vpc-pub-cdb.ntruss.com/mysql-db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ncp-user
    password: 1qaz@WSX@@
  profiles:
    include: oauth

# MyBatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml