# Server
server:
  port: 8090
  servlet:
    context-path: /

#


# DataBase
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${{secrets.db_url}}
    username: ${{secrets.db_username}}
    password: ${{secrets.db_password}}
  profiles:
    include: oauth
  OAuth2:  #social login
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id : 706072512947-9re2csup517dockpeem4a7tq777gvt9d.apps.googleusercontent.com
      client-secret: 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
      callback-url: http://localhost:8080/login/oauth2/code/google
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile






# MyBatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml


