name: Java CI with Gradle # Workflow 이름

on: # Workflow를 자동으로 트리거 하기 위한 이벤트
  push: # 특정 이벤트에 반응
    branches: [main] # main 브랜치로 push가 발생했을 때 실행
  pull_request: # PR 생성/수정 시 실행
    branches: [main]

jobs: # 병렬로 실행되는 작업 단위, 여러 step으로 이루어짐
  build:

    runs-on: ubuntu-latest # 스크립트를 작동할 OS

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # 현재 리포지토리의 코드를 체크아웃하여 워크플로우에서 사용할 수 있도록 한다

    - name: Set up JDK 17
      uses: actions/setup-java@v3 # 재사용 가능한 워크플로 파일의 위치 및 버전
      with:
        java-version: '17'
        distribution: 'oracle'
    
    # ./gradlw 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 프로젝트 build
    - name: Build with Gradle
      run: ./gradlew clean build -x test
