name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  S3_BUCKET_NAME: sebadogapp-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle 빌드 (테스트 생략)
      - name: Build project with Gradle
        run: ./gradlew clean build -x test

      # 5. 배포 디렉토리 생성
      - name: Create deploy directory
        run: mkdir -p deploy

      # 6. 빌드된 JAR 복사
      - name: Copy built JAR
        run: cp ./build/libs/*.jar ./deploy

      # 7. appspec.yml 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      # 8. 스크립트 복사
      - name: Copy deployment scripts
        run: cp ./scripts/*.sh ./deploy

      # 9. 압축 파일 생성
      - name: Create deployment ZIP
        run: zip -r ./project-artifact.zip ./deploy

      # 10. AWS 자격증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 11. S3에 업로드
      - name: Upload artifact to S3
        run: aws s3 cp --region ap-northeast-2 ./project-artifact.zip s3://${{ secrets.S3_BUCKET_NAME }}/

      # 12. CodeDeploy 배포 실행
      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name zerocost-application \
            --deployment-group-name zerocost-baepo \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=zerocost-deploy,bundleType=zip,key=project-artifact.zip \
            --region ap-northeast-2
